name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
      shell: bash

    - name: Install dependencies
      working-directory: ./python

      run: poetry install --path python

    - name: Lint code
      working-directory: ./python
      run: make lint

    - name: Test code
      working-directory: ./python
      run: make test

    - name: Check PR status
      run: |
        if [ -n "$(git diff --name-only ${{ github.base_ref }}..${{ github.head_ref }})" ]; then
          echo "Changes detected. Please make sure to push all changes to the branch before merging.";
          exit 1;
        fi
